# vim: set ft=yaml :


name: 'check'

on:
  push:

defaults:
  run:
    shell: 'sh -euo pipefail {0}'

permissions:
  contents: 'read'

jobs:
  check:
    # switch to 'ubuntu-latest' when 'ubuntu-26.04' becomes latest
    # https://github.com/actions/runner-images/issues/14226
    runs-on: 'ubuntu-26.04'
    steps:
      - uses: 'actions/checkout@v7'
      - uses: 'jdx/mise-action@v4'
      - run: 'mise run check'
      - run: 'mise run build'
