# vim: set ft=yaml :


name: 'Renovate'

on:
  schedule:
    - cron: '0 5 * * *'
      timezone: 'America/New_York'
  workflow_dispatch:


defaults:
  run:
    shell: 'sh -euo pipefail {0}'

permissions:
  contents: 'read'

jobs:

  renovate:
    name: 'Renovate'
    environment:
      name: 'renovate'
      deployment: false
    runs-on: 'ubuntu-26.04'
    steps:
      - name: 'Create GitHub app token'
        id: 'app-token'
        uses: 'actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1' # v3.2.0
        with:
          client-id: '${{ vars.RENOVATE_APP_CLIENT_ID }}'
          private-key: '${{ secrets.RENOVATE_APP_PRIVATE_KEY }}'
          owner: '${{ github.repository_owner }}'
          repositories: '${{ github.repository }}'
      - name: 'Checkout'
        uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7.0.1
      - name: 'Renovate'
        uses: 'renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c' # v46.2.5
        env:
          RENOVATE_ALLOWED_UNSAFE_EXECUTIONS: 'mise'
          RENOVATE_REPOSITORIES: '${{ github.repository }}'
        with:
          configurationFile: 'renovate.json'
          docker-cmd-file: '.github/renovate-entrypoint.sh'
          token: '${{ steps.app-token.outputs.token }}'
